### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by anton-kozlovsky** [soulless-viewer/shipments#2]
https://github.com/soulless-viewer/shipments/blob/master/src/api/requests.js#L13
Why not just add required headers to each request?

I would say that a code is over-complicated in some places. For instance, pagination could be done as easy as one method which sends a request with page parameter. This is basically what it does in the end, but in order to realize that I have to jump over several files. As I can see the whole app logic is placed in the store. I'm not sure what are the benefits of such approach. In my opinion it is easier and more clearly to keep data in the component if it won't be shared across the whole app.

Also, it would be nice to see better error handling. If something goes wrong a user should be notified.

Summary:
The code is just over-complicated or probably I'm a fool :)

**Comment by soulless-viewer** [comment]
@anton-kozlovsky
Thank you for your feedback!

Generally speaking, my code is really more difficult than it could be, but we should keep in mind that this was a test project _(which usually involves testing my skills)_, and also that I didn't have a clear technical task.

Considering the above, I decided to show that I'm able to work with various cases, such as: composition API, namespace store, etc.

**Comment by anton-kozlovsky** [comment]
Hm, probably task description should be precise about what we are focused on.
The idea is that we don't limit candidates, so we can understand what they see as a priority.
I don't have any in doubts in your technical skills. We are just trying to avoid engineers who are focused on the code too much.
Since you done that intentionally, we are good then.
